language: swift
xcode_workspace: EntropyKit.xcworkspace
branches:
  only:
  - master
osx_image: xcode11.3
matrix:
    include:
        - xcode_scheme: EntropyKit-macOS
        - xcode_scheme: EntropyKit-iOS
          xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro
        - xcode_scheme: EntropyKit-iOS
          xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro
        - xcode_scheme: EntropyKit-iOS
          xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro
        - xcode_scheme: EntropyKit-iOS
          xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro
