name: CI

on: [push]

jobs:
  build:
    # For more info see https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    runs-on: macos-latest
    strategy:
      matrix:
        target: [ "macOS", "iOS13.2.2", "iOS13.3", "iOS13.4" ]
        include:
          - target: "macOS"
            scheme: "EntropyKit-macOS"
            version: "11.3.1"
          - target: "iOS13.2.2"
            scheme: "EntropyKit-iOS"
            dest: "-destination 'platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro'"
            version: "11.2.1"
          - target: "iOS13.3"
            scheme: "EntropyKit-iOS"
            dest: "-destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro'"
            version: "11.3.1"
          - target: "iOS13.4"
            scheme: "EntropyKit-iOS"
            dest: "-destination 'platform=iOS Simulator,OS=13.4,name=iPhone 11 Pro'"
            version: "11.4_beta"
    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
    - name: Run Tests
      run: set -o pipefail && xcodebuild test -workspace EntropyKit.xcworkspace ${{ matrix.dest }} -scheme '${{ matrix.scheme }}' | xcpretty
